/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccordionItem: typeof import('./components/AccordionItem.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    EditableOrderList: typeof import('./components/EditableOrderList.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    FlashMessage: typeof import('./components/FlashMessage.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    Radio: typeof import('./components/Radio.vue')['default']
    RequireLabel: typeof import('./components/RequireLabel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTopButton: typeof import('./components/ScrollToTopButton.vue')['default']
    SingerButtonList: typeof import('./components/SingerButtonList.vue')['default']
    SingerSongAccordionList: typeof import('./components/SingerSongAccordionList.vue')['default']
    SingersSongList: typeof import('./components/SingersSongList.vue')['default']
    SlideContents: typeof import('./components/SlideContents.vue')['default']
    SongForm: typeof import('./components/SongForm.vue')['default']
    YoutubeThumbnail: typeof import('./components/YoutubeThumbnail.vue')['default']
  }
}
